### ISSUE TITLE
Docker-machine: command not found

### ISSUE THREAD

**Issue by Skillkiller** [Shaked/docker-whatsapp#1]
Hello,
I would like use this script, to install the whatsapp API, I get always this Error

```
root@387228:~/Docker# ./docker.sh
./docker.sh: line 2: docker-machine: command not found
./docker.sh: line 3: docker-machine: command not found
./docker.sh: line 4: docker-machine: command not found
docker - version 1.4
Copyright 2003, Ben Jansens <ben@orodu.net>

Usage: docker [OPTIONS]

Options:
  -help             Show this help.
  -display DISPLAY  The X display to connect to.
  -border           The width of the border to put around the
                    system tray icons. Defaults to 1.
  -vertical         Line up the icons vertically. Defaults to
                    horizontally.
  -wmaker           WindowMaker mode. This makes docker a
                    fixed size (64x64) to appear nicely in
                    in WindowMaker.
                    Note: In this mode, you have a fixed
                    number of icons that docker can hold.
  -iconsize SIZE    The size (width and height) to display
                    icons as in the system tray. Defaults to
                    24.
  -color COLOR      The background color to use for the tray.
                    Defaults to whatever color the window
                    manager specifies.
root@387228:~/Docker#

```

**Comment by Shaked** [comment]
Hey,

You need to install docker-machine
https://docs.docker.com/machine/install-machine/, I am assuming that you
are using linux, then you might need to run it differently,  meaning use
docker to run the commands in docker.sh instead of running docker.sh.

Does this help?

**Comment by Skillkiller** [comment]
After I installed docker-machine I get this Error

```
root@387228:~/Docker# ./docker.sh
Running pre-create checks...
Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
Host does not exist: "whatsapp"
Host does not exist: "whatsapp"
docker - version 1.4
Copyright 2003, Ben Jansens <ben@orodu.net>

Usage: docker [OPTIONS]

Options:
  -help             Show this help.
  -display DISPLAY  The X display to connect to.
  -border           The width of the border to put around the
                    system tray icons. Defaults to 1.
  -vertical         Line up the icons vertically. Defaults to
                    horizontally.
  -wmaker           WindowMaker mode. This makes docker a
                    fixed size (64x64) to appear nicely in
                    in WindowMaker.
                    Note: In this mode, you have a fixed
                    number of icons that docker can hold.
  -iconsize SIZE    The size (width and height) to display
                    icons as in the system tray. Defaults to
                    24.
  -color COLOR      The background color to use for the tray.
                    Defaults to whatever color the window
                    manager specifies.
root@387228:~/Docker#
```

Have you some like a "Getting Start" File for me ?

**Comment by Shaked** [comment]
Basically you'll have to install Virtual box for that as well. Maybe you
should follow the full docker installation process and then follow
docker.sh? In case you do it, it would be nice if you could write down what
you did in order to get it to work.

All the best

---

Shaked Klein Orbach
http://www.shakedos.com/about

**Comment by c0d3x27** [comment]
banginpadr:docker-whatsapp $ ./docker.sh
Host already exists: "whatsapp"
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.69.100:2696"
export DOCKER_CERT_PATH="/Users/Diango/.docker/machine/machines/whatsapp"
export DOCKER_MACHINE_NAME="whatsapp"
# Run this command to configure your shell: 
# eval $(docker-machine env whatsapp)
Sending build context to Docker daemon 71.68 kB
Step 1/37 : FROM ubuntu:15.04
 ---> d1b55fd07600
Step 2/37 : MAINTAINER Shaked KleinO Orbach <klein.shaked+whatsapp@gmail.com>
 ---> Using cache
 ---> c3217dc19f45
Step 3/37 : RUN apt-get update -y
 ---> Using cache
 ---> 377cc432673e
Step 4/37 : RUN apt-get install -y software-properties-common
 ---> Using cache
 ---> 1ef5288a610b
Step 5/37 : RUN add-apt-repository ppa:ondrej/php5-5.6
 ---> Running in b6c64ed2a259
Cannot add PPA: 'ppa:~ondrej/ubuntu/php5-5.6'.
The user named '~ondrej' has no PPA named 'ubuntu/php5-5.6'
Please choose from the following available PPAs:
 * 'apache2':  PPA for Apache 2.x
 * 'apache2-qa':  PPA for Apache2 (QA builds; experimental)
 * 'autotools':  PPA for autotools (not-supported; build-dependency; experimental)
 * 'bind9':  PPA for BIND 9
 * 'cmake':  PPA for CMake (not-supported, experimental)
 * 'common':  Common PPA packages
 * 'courier':  PPA for Courier MTA
 * 'cyrus-imapd':  PPA for Cyrus IMAP
 * 'debhelper':  PPA for Debhelper (and friends)
 * 'golang':  PPA for Go (experimental, build-dependency)
 * 'llvm':  PPA for LLVM
 * 'mariadb-10.0':  PPA for MariaDB 10.0 (don't use, broken)
 * 'mysql-5.5':  PPA for MySQL 5.5 (don't use, broken)
 * 'mysql-5.6':  PPA for MySQL 5.6 (don't use, broken)
 * 'mysql-5.7':  PPA for MySQL 5.7 (don't use, broken)
 * 'nginx':  PPA for NGINX with HTTP/2 on Ubuntu 12.04 LTS and higher
 * 'nginx-mainline':  PPA for NGINX Mainline with HTTP/2 on Ubuntu 12.04 LTS and higher
 * 'pelican':  PPA for Pelican
 * 'php':  ***** The main PPA for PHP (5.6, 7.0, 7.1) with many PECL extensions *****
 * 'php-qa':  PPA for PHP (QA builds; experimental)
 * 'php-zts':  PPA for PHP ZTS (experimental, unsupported)
 * 'php5-compat':  PPA with dummy compatibility php5* packages
 * 'php5-oldstable':  PPA for PHP 5.4 (unsupported, vulnerable)
 * 'pkg-dpkg':  dpkg and friends (very experimental)
 * 'pkg-gearman':  PPA for Gearman
 * 'pkg-nlnetlabs':  NLNetLabs Backported Packages
 * 'postfix+dane':  PPA for Postfix with DANE support
 * 'ppa':  PPA for Ondřej Surý
 * 'sandbox':  Sandbox for preparation of various packages (DON'T USE)
 * 'seafile':  PPA for Seafile
 * 'zonemaster':  PPA for Zonemaster
The command '/bin/sh -c add-apt-repository ppa:ondrej/php5-5.6' returned a non-zero code: 1
banginpadr:docker-whatsapp $ 

i keep getting this error. can you please help me? im using a mac
