### ISSUE TITLE
Problems using Docker Container

### ISSUE THREAD

**Issue by sushi86** [Shaked/docker-whatsapp#2]
Hey, thank you for offering that Dockerfile to get all the dependencies.

Right now I'm not using Docker a lot, so maybe you can help:

I've installed Docker on my Mac. I've cloned your Docker Repo and started to execute the docker.sh. Then a lot of things happened ( 10 -20 mins).

But now, how to go on? The next would be to execute 

```
docker run -i -t <hash> /bin/bash
```

where do I get the hash from?

When I do docker ps -a I don't see any containers.

Maybe you can help me, thank you =)

**Comment by Shaked** [comment]
Hey @sushi86 

All you need to do is `docker images` the hash will be shown there. In case you are facing an issue, please make sure that you ran eval `"$(docker-machine env whatsapp)"`.

Let me know if it worked,
Shaked

**Comment by sushi86** [comment]
Thank you for your answer, I like the idea to generate a docker Container for the library 👍 

but i'm still struggeling:

after doing ./docker.sh

I get:

```
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
```

But 

```
docker-machine ls
NAME       ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default    *        virtualbox   Running   tcp://192.168.99.100:2376           v1.11.2   
whatsapp   -        virtualbox   Running   tcp://192.168.99.102:2376           v1.11.2  
```

when I do ssh into that machine, I have no /whatsapp directory:

```
docker-machine ssh whatsapp
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.11.2, build HEAD : a6645c3 - Wed Jun  1 22:59:51 UTC 2016
Docker version 1.11.2, build b9f10c9
docker@whatsapp:~$ ls
log.log
docker@whatsapp:~$ cd /
docker@whatsapp:/$ ls
Users/   bin/     dev/     etc/     home/    init     lib/     lib64    linuxrc  mnt/     opt/     proc/    root/    run/     sbin/    sys/     tmp      usr/     var/
```

Sorry if this is dump elemental question. And thank you for your help!

**Comment by sushi86** [comment]
Ok, sorry, I see it by myself 
the whatsapp machine wasn't active, sorry :)

**Comment by SrDebiasi** [comment]
Hello suhsi, I'm new at docker, I have the same issue
 after doing ./docker.sh
I get:

```
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
```

Where can I find the hash?

What command I need to do now? Can u help me?
How can I active the whatsapp machine?
I tryed  
`docker machine active`

but I get :
`default`
